/** Permission codes — mirror backend apps/accounts catalog.
 * The backend is authoritative; these are only labels for checks. */

export const P = {
  usersView: "users.view",
  usersCreate: "users.create",
  usersUpdate: "users.update",
  usersDisable: "users.disable",
  usersManage: "users.manage",
  examsView: "exams.view",
  examsCreate: "exams.create",
  examsUpdate: "exams.update",
  examsTransition: "exams.transition",
  examsPublish: "exams.publish",
  examsArchive: "exams.archive",
  candidatesView: "candidates.view",
  candidatesCreate: "candidates.create",
  candidatesUpdate: "candidates.update",
  candidatesDelete: "candidates.delete",
  candidatesImport: "candidates.import",
  candidatesExport: "candidates.export",
  subjectsView: "subjects.view",
  subjectsManage: "subjects.manage",
  marksView: "marks.view",
  marksEnter: "marks.enter",
  marksUpdate: "marks.update",
  marksImport: "marks.import",
  marksExport: "marks.export",
  marksFinalize: "marks.finalize",
  marksApprove: "marks.approve",
  resultsView: "results.view",
  resultsCalculate: "results.calculate",
  resultsReview: "results.review",
  resultsApprove: "results.approve",
  resultsFinalize: "results.finalize",
  resultsPublish: "results.publish",
  resultsCorrect: "results.correct",
  resultsExport: "results.export",
  reportsView: "reports.view",
  reportsGenerate: "reports.generate",
  reportsExport: "reports.export",
  reportsPrint: "reports.print",
  reportsManageTemplates: "reports.manage_templates",
  smsSend: "sms.send",
  centersView: "centers.view",
  centersManage: "centers.manage",
  auditView: "audit.view",
  settingsManage: "settings.manage",
} as const

export type PermCode = (typeof P)[keyof typeof P]
